name: UI Asset (Overhaul Tracking)
description: Track creation, integration, and testing of a UI asset as part of the Complete UI Overhaul.
title: "[UI Overhaul] <Frame/Asset Name>"
labels: [asset, ui, overhaul, tracking, enhancement]
body:
  - type: input
    id: overhaul_category
    attributes:
      label: Overhaul Category
      description: Which major UI area or frame is this asset part of? (e.g. Store, Settings, HUD)
      placeholder: e.g. Store, HUD, Settings, Daily Rewards
    validations:
      required: true

  - type: input
    id: overhaul_priority
    attributes:
      label: Overhaul Priority
      description: What is the asset’s priority in the overhaul? (Critical, High, Medium, Low)
      placeholder: e.g. Critical
    validations:
      required: true

  - type: input
    id: ui_name
    attributes:
      label: Internal/Code Name
      description: What is the internal or code name for this UI asset?
      placeholder: e.g. inventory_menu
    validations:
      required: true

  - type: input
    id: display_name
    attributes:
      label: Display Name
      description: What is the display name shown to users (if different)?
      placeholder: e.g. Inventory Menu

  - type: textarea
    id: ui_description
    attributes:
      label: Description & Overhaul Goals
      description: Briefly describe the UI asset and what it's meant to improve in the overhaul (clarity, navigation, etc.).
      placeholder: e.g. Redesigned menu for managing player inventory, now with improved filtering and responsive layout.
    validations:
      required: true

  - type: input
    id: overhaul_checklist_mapping
    attributes:
      label: Overhaul Checklist Section(s)
      description: Reference the Overhaul Checklist item(s) this asset implements.
      placeholder: e.g. Store > Gamepasses; Settings > Accessibility

  - type: textarea
    id: design_refs
    attributes:
      label: Design/Figma Reference(s)
      description: Link to any design files, Figma, or visual references for this asset.
      placeholder: e.g. https://www.figma.com/file/...

  - type: dropdown
    id: wireframe_status
    attributes:
      label: Wireframe Status
      description: Status of the initial wireframe or design mockup.
      options:
        - Not Started
        - In Progress
        - Complete
    validations:
      required: true

  - type: dropdown
    id: design_status
    attributes:
      label: Design Status
      description: Status of the finalized design (Figma, Photoshop, etc).
      options:
        - Not Started
        - In Progress
        - Complete
    validations:
      required: true

  - type: dropdown
    id: imported_studio
    attributes:
      label: Imported Into Studio
      description: Has the asset been imported into Roblox Studio?
      options:
        - Not Started
        - In Progress
        - Complete
    validations:
      required: true

  - type: dropdown
    id: imported_codebase
    attributes:
      label: Imported Into Codebase
      description: Has the UI been integrated into the codebase?
      options:
        - Not Started
        - In Progress
        - Complete
    validations:
      required: true

  - type: dropdown
    id: tested_status
    attributes:
      label: Tested
      description: Has the UI asset been tested (manual/automated)?
      options:
        - Not Started
        - In Progress
        - Complete
    validations:
      required: true

  - type: textarea
    id: overhaul_testing_notes
    attributes:
      label: Overhaul Testing Notes
      description: Any special testing focus for the overhaul (e.g. clarity, accessibility, feedback from new users).
      placeholder: e.g. Verify clarity for new users, test on multiple devices, check accessibility scaling.

  - type: textarea
    id: implementation_pr
    attributes:
      label: Pull Requests / Commits
      description: Link to any relevant PRs or commits for this asset.
      placeholder: e.g. #123, commit abc456

  - type: textarea
    id: notes
    attributes:
      label: Notes & Blockers
      description: Anything else to note? Any blockers or dependencies?
      placeholder: e.g. Waiting on UX approval, requires API update, etc.
````We're waiting for you to approve the branch creation so we can continue with the pull request for the revamped UI asset issue template.
