name: UI Asset Tracking
description: Track creation and implementation progress of a UI asset, including design, import, development, and testing.
title: "[UI Asset] <UI Name>"
labels: [asset, ui, tracking, enhancement]
body:
  - type: input
    id: ui_name
    attributes:
      label: UI Name (Internal/Code Name)
      description: What is the internal or code name for this UI asset?
      placeholder: e.g. inventory_menu
    validations:
      required: true

  - type: input
    id: display_name
    attributes:
      label: Display Name
      description: What is the display name shown to users (if different)?
      placeholder: e.g. Inventory Menu

  - type: textarea
    id: ui_description
    attributes:
      label: Description
      description: Briefly describe the UI asset, its purpose, and key features.
      placeholder: e.g. Menu for managing player inventory, supports drag & drop, responsive layout.
    validations:
      required: true

  - type: dropdown
    id: wireframe_status
    attributes:
      label: Wireframe Status
      description: Status of the initial wireframe or design mockup.
      options:
        - Not Started
        - In Progress
        - Complete
    validations:
      required: true

  - type: dropdown
    id: design_status
    attributes:
      label: Design Status
      description: Status of the finalized design (Figma, Photoshop, etc).
      options:
        - Not Started
        - In Progress
        - Complete
    validations:
      required: true

  - type: dropdown
    id: imported_studio
    attributes:
      label: Imported Into Studio
      description: Has the asset been imported into Roblox Studio?
      options:
        - Not Started
        - In Progress
        - Complete
    validations:
      required: true

  - type: dropdown
    id: imported_vide
    attributes:
      label: Imported Into VIDE
      description: Has the asset been imported into VIDE (if applicable)?
      options:
        - Not Applicable
        - Not Started
        - In Progress
        - Complete

  - type: dropdown
    id: imported_codebase
    attributes:
      label: Imported Into Codebase
      description: Has the UI been integrated into the codebase?
      options:
        - Not Started
        - In Progress
        - Complete
    validations:
      required: true

  - type: dropdown
    id: reactive_props
    attributes:
      label: Reactive Props Implemented
      description: Are UI reactive props (for data-driven updates) implemented?
      options:
        - Not Applicable
        - Not Started
        - In Progress
        - Complete

  - type: dropdown
    id: storybook_status
    attributes:
      label: Story/Component Demo
      description: Has a story or component demo (e.g. Storybook) been created?
      options:
        - Not Applicable
        - Not Started
        - In Progress
        - Complete

  - type: dropdown
    id: player_data_synced
    attributes:
      label: Player-Data Synced
      description: Is the UI synced with player-data as required?
      options:
        - Not Applicable
        - Not Started
        - In Progress
        - Complete

  - type: dropdown
    id: tested_status
    attributes:
      label: Tested
      description: Has the UI asset been tested (manual/automated)?
      options:
        - Not Started
        - In Progress
        - Complete
    validations:
      required: true

  - type: dropdown
    id: finalized_status
    attributes:
      label: Finalized/Ready for Release
      description: Is the asset finalized and ready for use/deployment?
      options:
        - Not Started
        - In Progress
        - Complete
    validations:
      required: true

  - type: textarea
    id: implementation_pr
    attributes:
      label: Pull Requests / Commits
      description: Link to any relevant PRs or commits where this asset is being implemented.
      placeholder: e.g. #123, commit abc456

  - type: textarea
    id: notes
    attributes:
      label: Notes & Blockers
      description: Anything else to note? Any blockers or dependencies?
      placeholder: e.g. Waiting on UX approval, requires API update, etc.
